import Link from "next/link";
import { ArrowUpRight, Layers3, Plus } from "lucide-react";
import { analyticsApps } from "@/lib/apps";

export default function Home() {
  return <div>
    <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-2 text-sm font-medium text-[var(--accent)]">数据工作台</p><h1 className="text-3xl font-semibold tracking-[-.035em] sm:text-4xl">Henri 的产品，一处看清</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--secondary)] sm:text-base">按应用组织分析页面。先从 Edit Page 开始，后续的新产品可以沿用同一套导航、身份和数据组件。</p></div><div className="flex items-center gap-2 rounded-full border bg-white px-3 py-1.5 text-xs text-[var(--secondary)]"><span className="size-2 rounded-full bg-emerald-500" />系统正常</div></div>
    <section className="mt-10"><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-semibold">应用</h2><span className="text-xs text-[var(--subtle)]">{analyticsApps.length} 个已配置</span></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{analyticsApps.map((app) => <Link key={app.slug} href={app.slug} className="group rounded-2xl border bg-white p-5 shadow-[0_1px_2px_rgb(15_23_42/.025)] transition hover:-translate-y-0.5 hover:border-[#bdc8c1] hover:shadow-[0_8px_28px_rgb(20_40_30/.07)]"><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-xl bg-[#e8f0eb] text-[var(--accent)]"><app.icon size={21} /></span><ArrowUpRight size={18} className="text-[var(--subtle)] transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5 group-hover:text-[var(--ink)]" /></div><h3 className="mt-8 text-lg font-semibold">{app.name}</h3><p className="mt-1.5 text-sm leading-6 text-[var(--secondary)]">{app.description}</p><div className="mt-5 flex items-center gap-2 text-xs text-amber-700"><span className="size-1.5 rounded-full bg-amber-400" />等待接入数据</div></Link>)}<div className="flex min-h-56 flex-col items-center justify-center rounded-2xl border border-dashed bg-white/35 p-5 text-center"><span className="grid size-10 place-items-center rounded-full bg-white text-[var(--subtle)] shadow-sm"><Plus size={19} /></span><p className="mt-4 text-sm font-medium">下一个 Henri 应用</p><p className="mt-1 text-xs text-[var(--subtle)]">按独立 slug 接入</p></div></div></section>
    <section className="mt-10 grid gap-4 md:grid-cols-3"><Info icon={<Layers3 size={17} />} label="统一结构" value="应用级路由" /><Info label="身份认证" value="auth.henriz.dev" /><Info label="数据状态" value="尚未接入" /></section>
  </div>;
}

function Info({ icon, label, value }: { icon?: React.ReactNode; label: string; value: string }) { return <div className="rounded-xl border bg-white/65 px-4 py-3"><div className="flex items-center gap-2 text-xs text-[var(--subtle)]">{icon}{label}</div><div className="mt-1.5 text-sm font-medium">{value}</div></div>; }
